import streamlit as st
import pandas as pd
import subprocess
import time
import os

# ---------------------------------------------------------
# UI CONFIGURATION
# ---------------------------------------------------------
st.set_page_config(
    page_title="Sentinel Lab | Risk Engine",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for "HFT" vibe
st.markdown("""
    <style>
        .metric-card {
            background-color: #0e1117;
            border: 1px solid #30333d;
            padding: 20px;
            border-radius: 10px;
        }
        .stButton>button {
            width: 100%;
            border-radius: 5px;
            height: 3em;
            background-color: #00ff41;
            color: black;
            font-weight: bold;
        }
    </style>
""", unsafe_allow_html=True)

# ---------------------------------------------------------
# HEADER
# ---------------------------------------------------------
col1, col2 = st.columns([3, 1])
with col1:
    st.title("🛡️ Sentinel Lab")
    st.caption("Hardware-Accelerated Settlement Risk Simulator")
with col2:
    st.metric("System Status", "ONLINE", "200 MHz Clock")

st.markdown("---")

# ---------------------------------------------------------
# SIDEBAR CONTROLS
# ---------------------------------------------------------
st.sidebar.header("🔬 Simulation Config")
scenario = st.sidebar.selectbox(
    "Risk Scenario",
    ("DDoS Attack (10k TXs)", "Random Market (5k TXs)", "Flash Crash (Coming Soon)")
)

st.sidebar.markdown("### Parameters")
users = st.sidebar.slider("Active Agents", 100, 1024, 1024)
latency_target = st.sidebar.slider("Max Latency (ns)", 10, 100, 20)

# ---------------------------------------------------------
# MAIN EXECUTION ENGINE
# ---------------------------------------------------------
def run_simulation(scenario_name):
    """Triggers the Python Runner and captures output"""
    
    # Map selection to file
    csv_file = "data/scenario_ddos.csv" if "DDoS" in scenario_name else None
    
    cmd = ["python3", "run_lab.py"]
    if csv_file:
        cmd += ["--scenario", csv_file]
        
    with st.spinner(f"🚀 Initializing Verilator... Injecting {scenario_name}..."):
        # Artificial sleep to make the UI feel "heavy" (users like seeing loading bars)
        time.sleep(0.5) 
        result = subprocess.run(cmd, capture_output=True, text=True)
        
    return result

# ---------------------------------------------------------
# METRICS DISPLAY
# ---------------------------------------------------------
# Create 4 columns for KPIs
kpi1, kpi2, kpi3, kpi4 = st.columns(4)

# Placeholder for dynamic updates
with kpi1:
    tps_display = st.empty()
    tps_display.metric("Throughput (TPS)", "0.00 M", "0%")

with kpi2:
    lat_display = st.empty()
    lat_display.metric("Settlement Latency", "0 ns", "0%")

with kpi3:
    vol_display = st.empty()
    vol_display.metric("Batch Volume", "0 TXs")

with kpi4:
    status_display = st.empty()
    status_display.info("Ready to Simulate")

# ---------------------------------------------------------
# RUN LOGIC
# ---------------------------------------------------------
if st.button("RUN SIMULATION"):
    # 1. Run the Engine
    res = run_simulation(scenario)
    
    if res.returncode == 0:
        # 2. Success! Read Data
        status_display.success("Settled")
        
        try:
            # Parse the CSV logs generated by run_lab.py
            df = pd.read_csv("logs/sim_stats.csv", index_col=0)
            
            tps_val = float(df.loc["tps_million"].iloc[0])
            total_tx = int(df.loc["total_tx"].iloc[0])
            duration_ms = float(df.loc["duration_ns"].iloc[0]) / 1e6
            
            # 3. Update Metrics with Animation
            tps_display.metric("Throughput (TPS)", f"{tps_val:.2f} M", "⚡ Hardware Speed")
            lat_display.metric("Settlement Latency", "10 ns", "-99% vs Solana") # 2 cycles @ 200MHz
            vol_display.metric("Batch Volume", f"{total_tx:,}", f"{duration_ms:.2f} ms")
            
            # 4. Show "Telemetry" (The Graphs)
            st.markdown("### 📊 Live Telemetry")
            chart1, chart2 = st.columns(2)
            
            with chart1:
                st.markdown("**Latency Comparison (Log Scale)**")
                perf_data = pd.DataFrame({
                    "System": ["Solana (L1)", "Arbitrum (L2)", "Sentinel (HW)"],
                    "Latency (ms)": [400, 100, 0.00001]
                })
                st.bar_chart(perf_data.set_index("System"))
                
            with chart2:
                st.markdown("**Throughput Ramp-Up**")
                # Mock ramp-up curve for visual effect based on final TPS
                ramp = [0, tps_val*0.2, tps_val*0.5, tps_val*0.8, tps_val, tps_val]
                st.line_chart(ramp)
                
            with st.expander("View Raw Hardware Logs"):
                st.code(res.stdout, language="bash")
                
        except Exception as e:
            st.error(f"Error reading telemetry: {e}")
    else:
        status_display.error("Crashed")
        st.error("Simulation Failed")
        st.code(res.stderr)
